### ISSUE TITLE
Display text extract on individual page

### ISSUE THREAD

**Issue by Jen-Harris** [FAC-11/litlearn#9] opened 2017-09-05 13:44 UTC
We need to show the text extract prior to showing the question to allow the user a chance to understand the text without the distraction of a question. 

User story: "Before answering a question, I will have a chance to read the question text extract in advance"

To complete this issue we need to: 
  - [ ] large font version of the extract
  - [ ] large font version of the question
  - [ ] distinctive 'question' page format
- [ ] Be able to navigate to the question, back a screen or to the home page

**Comment by rachaelcodes** [comment] 2017-09-05 14:53
duplicate of #20

**Closed by rachaelcodes** 2017-09-05 14:53 UTC
Labels: duplicate, priority-2
